version: '3.8'
services:

  db:
    image: mysql:5.7
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: mydb
    volumes:
      - db-data:/var/lib/mysql
      - ./html/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  web:
    build: .
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: mydb
    restart: always
    links:
      - db
  
volumes:
  db-data:

#http://localhost/create.php
# Слава Омниссии!!!


